--
-- PostgreSQL database dump
--

\restrict rZYddUZwwsv3gydoU2nRdx6jROdYw8uB8YPkOJIe1wY8eWwYzIWoV3UXQt2ZfAa

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes (
    id integer NOT NULL,
    nome character varying(150) NOT NULL,
    email character varying(256) NOT NULL,
    telefone character varying(20) NOT NULL,
    data_cadastro timestamp with time zone NOT NULL,
    bairro character varying(100),
    cep character varying(8),
    cnpj character varying(14),
    cpf character varying(11),
    logradouro character varying(200),
    municipio character varying(100),
    razao_social character varying(200),
    uf character varying(2)
);


--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contas_pagar; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contas_pagar (
    id integer NOT NULL,
    descricao character varying(200) NOT NULL,
    fornecedor character varying(150) NOT NULL,
    valor numeric(12,2) NOT NULL,
    data_vencimento timestamp with time zone NOT NULL,
    data_pagamento timestamp with time zone,
    data_cadastro timestamp with time zone NOT NULL,
    forma_pagamento character varying(20)
);


--
-- Name: contas_pagar_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contas_pagar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contas_pagar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contas_receber; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contas_receber (
    id integer NOT NULL,
    cliente_id integer NOT NULL,
    descricao character varying(200) NOT NULL,
    valor numeric(12,2) NOT NULL,
    data_vencimento timestamp with time zone NOT NULL,
    data_recebimento timestamp with time zone,
    data_cadastro timestamp with time zone NOT NULL,
    forma_pagamento character varying(20),
    ordem_servico_id integer
);


--
-- Name: contas_receber_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contas_receber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contas_receber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estoque; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estoque (
    id integer NOT NULL,
    nome character varying(200) NOT NULL,
    descricao character varying(500),
    quantidade numeric(10,2) NOT NULL,
    preco_compra numeric(10,2) NOT NULL,
    preco_venda numeric(10,2) NOT NULL,
    estoque_minimo numeric(10,2) NOT NULL,
    data_cadastro timestamp with time zone NOT NULL
);


--
-- Name: estoque_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estoque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estoque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itens_ordem_servico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.itens_ordem_servico (
    id integer NOT NULL,
    ordem_servico_id integer NOT NULL,
    descricao character varying(200) NOT NULL,
    quantidade numeric(10,2) NOT NULL,
    valor_unitario numeric(10,2) NOT NULL,
    estoque_id integer
);


--
-- Name: itens_ordem_servico_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.itens_ordem_servico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_ordem_servico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ordens_servico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ordens_servico (
    id integer NOT NULL,
    cliente_id integer NOT NULL,
    veiculo_id integer NOT NULL,
    tecnico_id uuid,
    status character varying(20) NOT NULL,
    descricao_problema text NOT NULL,
    diagnostico text,
    solucao text,
    data_abertura timestamp with time zone NOT NULL,
    previsao_termino timestamp with time zone,
    data_conclusao timestamp with time zone,
    valor_mao_de_obra numeric(10,2) NOT NULL,
    desconto numeric(10,2) NOT NULL,
    aprovacao_cliente_em timestamp with time zone,
    aprovacao_cliente_nome character varying(150)
);


--
-- Name: ordens_servico_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ordens_servico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ordens_servico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id uuid NOT NULL,
    nome character varying(150) NOT NULL,
    email character varying(256) NOT NULL,
    role character varying(20) NOT NULL,
    data_criacao_utc timestamp with time zone NOT NULL,
    telefone character varying(20) NOT NULL,
    senha_hash character varying(60) DEFAULT ''::character varying NOT NULL,
    tema character varying(10) DEFAULT 'light'::character varying NOT NULL
);


--
-- Name: veiculos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.veiculos (
    id integer NOT NULL,
    cliente_id integer NOT NULL,
    placa character varying(10) NOT NULL,
    marca character varying(50) NOT NULL,
    modelo character varying(50) NOT NULL,
    ano integer NOT NULL,
    cor character varying(30) NOT NULL,
    data_cadastro timestamp with time zone NOT NULL,
    tipo character varying(20) DEFAULT 'Carro'::character varying NOT NULL
);


--
-- Name: veiculos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.veiculos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.veiculos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260901002325_RecreateUsuarios	10.0.11
20260901002720_InitialCreate	10.0.11
20260901010532_AddSenhaHashToUsuarios	10.0.11
20260901104846_AddVeiculos	10.0.11
20260901110634_AddContasPagarEContasReceber	10.0.11
20260903201328_AddUniqueIndexUsuarioEmail	10.0.11
20260903215250_AddFormaPagamentoContasPagarEContasReceber	10.0.11
20260904115813_AddDocumentoEnderecoCliente	10.0.11
20260904151415_AddIndiceUnicoCpfCnpjCliente	10.0.11
20260904210552_AddOrdensServico	10.0.11
20260905220549_AddOrdemServicoIdToContasReceber	10.0.11
20260905223004_ContaReceberCascadeAoDeletarOS	10.0.11
20260906000843_AddEstoque	10.0.11
20260908211954_AddTemaToUsuarios	10.0.11
20260908224015_AddTipoToVeiculos	10.0.11
\.


--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clientes (id, nome, email, telefone, data_cadastro, bairro, cep, cnpj, cpf, logradouro, municipio, razao_social, uf) FROM stdin;
40	MERCANTIL DO BRASIL	mercantil@mercantil.com.br	3130575342	2026-09-04 12:09:42.472745+00	SAVASSI	30110042	17184037000110	\N	DO CONTORNO	BELO HORIZONTE	BANCO MERCANTIL DO BRASIL SA	MG
\.


--
-- Data for Name: contas_pagar; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.contas_pagar (id, descricao, fornecedor, valor, data_vencimento, data_pagamento, data_cadastro, forma_pagamento) FROM stdin;
263	fdfdfd	fdfd	20000.00	2026-09-15 00:00:00+00	\N	2026-09-05 23:39:45.854302+00	\N
\.


--
-- Data for Name: contas_receber; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.contas_receber (id, cliente_id, descricao, valor, data_vencimento, data_recebimento, data_cadastro, forma_pagamento, ordem_servico_id) FROM stdin;
19	40	OS #20 — sfsdfsdf	3020.00	2026-10-07 00:00:00+00	\N	2026-09-08 23:21:48.117147+00	\N	20
\.


--
-- Data for Name: estoque; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.estoque (id, nome, descricao, quantidade, preco_compra, preco_venda, estoque_minimo, data_cadastro) FROM stdin;
2	Filtro de Oleo	txt	0.00	200.00	300.00	200.00	2026-09-06 00:19:23.194682+00
\.


--
-- Data for Name: itens_ordem_servico; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.itens_ordem_servico (id, ordem_servico_id, descricao, quantidade, valor_unitario, estoque_id) FROM stdin;
25	20	Filtro de Oleo	10.00	300.00	2
\.


--
-- Data for Name: ordens_servico; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.ordens_servico (id, cliente_id, veiculo_id, tecnico_id, status, descricao_problema, diagnostico, solucao, data_abertura, previsao_termino, data_conclusao, valor_mao_de_obra, desconto, aprovacao_cliente_em, aprovacao_cliente_nome) FROM stdin;
21	40	7	b251ae12-fe0d-4fa0-ab7a-c009b9f5a71c	Aberto	dsdasdas	d	\N	2026-09-08 22:27:02.946789+00	2026-09-09 00:00:00+00	2026-09-17 00:00:00+00	32323.23	10.00	\N	\N
20	40	7	5f98d6f0-e641-4a4e-b1c2-06f9832e6f83	Concluído	sfsdfsdf	fdfd	fd	2026-09-06 17:07:49.56821+00	2026-09-07 00:00:00+00	2026-09-07 00:00:00+00	20.00	0.00	\N	\N
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios (id, nome, email, role, data_criacao_utc, telefone, senha_hash, tema) FROM stdin;
02e7168f-a2d2-4f6b-934d-f4d77c109980	sdsdsd	ddssds@gmail.com	Recepcionista	2026-09-03 22:50:45.859587+00	(22) 22222-2222	$2a$11$7dnfUWnUMF.Q2kbxa9D6yuIDS5PGSE.Fio9QWcmnscyOgOqqSq5ha	light
b251ae12-fe0d-4fa0-ab7a-c009b9f5a71c	Júnior Cergio	juniorcergio@gmail.com	Admin	2026-09-01 20:42:42.622593+00	(00) 00000-0000	$2a$11$dpBHjAWfkDvdhja50ednMuZTFOJmu/CG8JWsU63yMbmDO/iYZ0b/m	light
5f98d6f0-e641-4a4e-b1c2-06f9832e6f83	Carla costa 	carla@gmail.com	Financeiro	2026-09-03 22:48:19.712247+00	(33) 33333-3333	$2a$11$uBsI0cA2n3nEAUTXuITXIevAEKO7nBxQYRKrNilLmzh4NwkjQYTfG	dark
\.


--
-- Data for Name: veiculos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.veiculos (id, cliente_id, placa, marca, modelo, ano, cor, data_cadastro, tipo) FROM stdin;
7	40	BRA2E19	FIAT	UNO	2025	PRETO	2026-09-04 21:23:15.365838+00	Carro
\.


--
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clientes_id_seq', 44, true);


--
-- Name: contas_pagar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.contas_pagar_id_seq', 263, true);


--
-- Name: contas_receber_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.contas_receber_id_seq', 19, true);


--
-- Name: estoque_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.estoque_id_seq', 2, true);


--
-- Name: itens_ordem_servico_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.itens_ordem_servico_id_seq', 25, true);


--
-- Name: ordens_servico_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ordens_servico_id_seq', 21, true);


--
-- Name: veiculos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.veiculos_id_seq', 9, true);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: clientes PK_clientes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT "PK_clientes" PRIMARY KEY (id);


--
-- Name: contas_pagar PK_contas_pagar; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contas_pagar
    ADD CONSTRAINT "PK_contas_pagar" PRIMARY KEY (id);


--
-- Name: contas_receber PK_contas_receber; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contas_receber
    ADD CONSTRAINT "PK_contas_receber" PRIMARY KEY (id);


--
-- Name: estoque PK_estoque; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estoque
    ADD CONSTRAINT "PK_estoque" PRIMARY KEY (id);


--
-- Name: itens_ordem_servico PK_itens_ordem_servico; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_ordem_servico
    ADD CONSTRAINT "PK_itens_ordem_servico" PRIMARY KEY (id);


--
-- Name: ordens_servico PK_ordens_servico; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_servico
    ADD CONSTRAINT "PK_ordens_servico" PRIMARY KEY (id);


--
-- Name: usuarios PK_usuarios; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT "PK_usuarios" PRIMARY KEY (id);


--
-- Name: veiculos PK_veiculos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veiculos
    ADD CONSTRAINT "PK_veiculos" PRIMARY KEY (id);


--
-- Name: IX_clientes_cnpj; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_clientes_cnpj" ON public.clientes USING btree (cnpj);


--
-- Name: IX_clientes_cpf; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_clientes_cpf" ON public.clientes USING btree (cpf);


--
-- Name: IX_contas_receber_cliente_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_contas_receber_cliente_id" ON public.contas_receber USING btree (cliente_id);


--
-- Name: IX_contas_receber_ordem_servico_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_contas_receber_ordem_servico_id" ON public.contas_receber USING btree (ordem_servico_id);


--
-- Name: IX_itens_ordem_servico_estoque_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_itens_ordem_servico_estoque_id" ON public.itens_ordem_servico USING btree (estoque_id);


--
-- Name: IX_itens_ordem_servico_ordem_servico_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_itens_ordem_servico_ordem_servico_id" ON public.itens_ordem_servico USING btree (ordem_servico_id);


--
-- Name: IX_ordens_servico_cliente_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ordens_servico_cliente_id" ON public.ordens_servico USING btree (cliente_id);


--
-- Name: IX_ordens_servico_tecnico_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ordens_servico_tecnico_id" ON public.ordens_servico USING btree (tecnico_id);


--
-- Name: IX_ordens_servico_veiculo_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ordens_servico_veiculo_id" ON public.ordens_servico USING btree (veiculo_id);


--
-- Name: IX_usuarios_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_usuarios_email" ON public.usuarios USING btree (email);


--
-- Name: IX_veiculos_cliente_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_veiculos_cliente_id" ON public.veiculos USING btree (cliente_id);


--
-- Name: contas_receber FK_contas_receber_clientes_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contas_receber
    ADD CONSTRAINT "FK_contas_receber_clientes_cliente_id" FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE RESTRICT;


--
-- Name: contas_receber FK_contas_receber_ordens_servico_ordem_servico_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contas_receber
    ADD CONSTRAINT "FK_contas_receber_ordens_servico_ordem_servico_id" FOREIGN KEY (ordem_servico_id) REFERENCES public.ordens_servico(id) ON DELETE CASCADE;


--
-- Name: itens_ordem_servico FK_itens_ordem_servico_estoque_estoque_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_ordem_servico
    ADD CONSTRAINT "FK_itens_ordem_servico_estoque_estoque_id" FOREIGN KEY (estoque_id) REFERENCES public.estoque(id) ON DELETE SET NULL;


--
-- Name: itens_ordem_servico FK_itens_ordem_servico_ordens_servico_ordem_servico_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_ordem_servico
    ADD CONSTRAINT "FK_itens_ordem_servico_ordens_servico_ordem_servico_id" FOREIGN KEY (ordem_servico_id) REFERENCES public.ordens_servico(id) ON DELETE CASCADE;


--
-- Name: ordens_servico FK_ordens_servico_clientes_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_servico
    ADD CONSTRAINT "FK_ordens_servico_clientes_cliente_id" FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE RESTRICT;


--
-- Name: ordens_servico FK_ordens_servico_usuarios_tecnico_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_servico
    ADD CONSTRAINT "FK_ordens_servico_usuarios_tecnico_id" FOREIGN KEY (tecnico_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;


--
-- Name: ordens_servico FK_ordens_servico_veiculos_veiculo_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_servico
    ADD CONSTRAINT "FK_ordens_servico_veiculos_veiculo_id" FOREIGN KEY (veiculo_id) REFERENCES public.veiculos(id) ON DELETE RESTRICT;


--
-- Name: veiculos FK_veiculos_clientes_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veiculos
    ADD CONSTRAINT "FK_veiculos_clientes_cliente_id" FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict rZYddUZwwsv3gydoU2nRdx6jROdYw8uB8YPkOJIe1wY8eWwYzIWoV3UXQt2ZfAa

